[secrets]
SABERSIM_API_KEY = "AIzaSyB-UBUIJ9I76bTTFbriypJGR__FW-c47FM"
SABERSIM_EMAIL = "adamjohnson24@dispostable.com"
SABERSIM_PASSWORD = "password123"
ODDS_API_KEY = "eeea42d1ab3c63cd997c3f4e074b0082"
